### ISSUE TITLE
Zadanie 2 / Pierwszy egzamin 2014

### ISSUE THREAD

**Issue by earlgreyz** [wakacjezmd/wakacjezmd.github.io#13]
**Nieprawidłowy wynik**
Powinno wyjść _4262_ (dowód przez brute w c++ [abcde.cpp.txt](https://github.com/wakacjezmd/wakacjezmd.github.io/files/317096/abcde.cpp.txt))

Prawidłowe rozwiązanie z zasady włączeń i wyłączeń, 

![img_20160615_220304](https://cloud.githubusercontent.com/assets/6977403/16095539/559d8aea-3345-11e6-9f76-f71b29958cdf.jpg)

**Comment by 0mp** [comment]
Dzięki, rozwiązanie zostało poprawione.

**Comment by styczynski** [comment]
# Można też wykładniczymi funkcjami tworzącymi

* *1.)* Litera występuje co najwyżej raz: `(1+x)`
* *2.)* Litera występuje co najmniej raz: `(x + x^2/2! + x^3/3! + ...) = (e^x - 1)`
* *3.)* Litera występuje dowolną ilość razy: `(1 + x + x^2/2! + x^3/3! + ... ) = e^x`

W sumie mamy **dwie litery typu 1**, **dwie litery typu 2** i **jedną literę typu 3**

Stąd mamy funkcję tworzącą:
```
  (1+x)(1+x)(e^x - 1)(e^x - 1)(e^x)
```

Co nam daje po wymnożeniu:
```
  ( exp(3x)-2*exp(2x)+exp(x) ) * ( 1 + x^2 + 2x )
```

Czyli:
```
  ( exp(3x) - 2*exp(2x) + exp(x) )  +
  ( x^2*exp(3x) - 2*x^2*exp(2x) + x^2*exp(x) )  +
  2 * ( x*exp(3x) - 2*x*exp(2x) + x*exp(x) ) 
```

Badamy współczynnik przy wyrazie `x^6/6!`

W ogólności warto zauważyć że jeśli mamy funkcję<br>`x^a * exp(bx)` to współczynnik przy wyrazie<br> `x^k/k!`<br>to jest<br>`b^(k-a) * (k-a+1) * (k-a+2) * ... * (k-1) * (k)`

Podstawiając do tego wzoru odpowiednie wyrazy funkcji tworzącej mamy:

```
  ( 3^6 + 2*2^6 + 1 ) +
  ( 5*6*3^4 - 5*6*2*2^4 + 5*6 ) +
  2 * ( 6*3^5 - 6*2*2^5 + 6 )
```

Po zsumowaniu: ` 4262 `

Tą metodą **wszystko idzie mechanicznie** jeśli się biegle liczy to zadanie zajmuje mniej niż minutę i zastanawiać się trzeba tylko na początku.

**Comment by styczynski** [comment]
@0mp Możesz dodać to rozwiązanie jeśli uznasz że warto 🚀 👍

**Comment by 0mp** [comment]
Dzięki! Wygląda spoko. Zachęcam do wysłania PR. Dużo więcej osób skorzysta z tego rozwiązania, jeżeli nie będzie ono zagubione w zamkniętych issues. 😄 

Miłego wieczoru.
