### ISSUE TITLE
2013 pierwszy termin, błąd w rozwiązaniu

### ISSUE THREAD

**Issue by pawliszak** [wakacjezmd/wakacjezmd.github.io#2]
W rozwiązaniu jest zła odpowiedź, 376 mod 11 to 2, a nie 10. Rozwiązaniem zadania powinno być 10.

**Comment by apaszke** [comment]
Faktycznie. Jednak kiedy powtarzam wzór z konstruktywnego ChTwoR, to cały czas dostaje takie same równanie. Wiesz co jest tam nie tak?

**Comment by apaszke** [comment]
Ok, mam to. Dzięki za uwagę! :+1:
