### ISSUE TITLE
Strony z rozwiązaniami wyświetlają się niepoprawnie

### ISSUE THREAD

**Issue by 0mp** [wakacjezmd/wakacjezmd.github.io#27]
![Błędnie wyświetlana strona.](https://user-images.githubusercontent.com/7978161/27109318-669004b0-50a2-11e7-9fb3-401427b90175.png)

1. Rozwiązania nie są domyślnie ukryte.
2. Tytuł strony jest powtórzony.

Problem istnieje tylko na GitHubie - testując lokalnie Jekyll zachowuje się zgodnie z oczekiwaniami.

**Comment by mikolaj-pirog** [comment]
Naprawione przez #54
