### ISSUE TITLE
Wskazówki do zadań

### ISSUE THREAD

**Issue by mikolaj-pirog** [wakacjezmd/wakacjezmd.github.io#46]
Zadania z MD mają to do siebie, że są trudne, ale mają proste rozwiązania. Często można głowić się nad zadaniem godzinami, próbować ugryźć z różnych stron, ale nie idzie, bo zwyczajnie nie widzimy tej jednej, kluczowej, obserwacji.

W takiej sytuacji można odczytać rozwiązanie, które rozwiewa wszystkie wątpliwości. Jest to jednak postępowanie nie do końca idealne przy nauce, gdyż najefektywniejsze jest wymyślanie rozwiązań samemu - najwięcej wtedy się wynosi. 

Rozwiązaniem pośrednim pomiędzy zaspojlerowaniem sobie rozwiązania, a patrzeniem godzinami w kartkę, są wskazówki do zadań - delikatne popchnięcie w właściwym kierunku, które jednak nie psuje zadania.

To właśnie chcę zasugerować - dodanie do zadań wskazówek, na przykład w postaci rozwijanego pola. Sądzę, że usprawniłoby to naukę MD, z powodów opisanych wyżej.

**Comment by 0mp** [comment]
Brzmi super. Jeśli pojawią się patche dodające takie wskazówki, to na pewno nie będę protestował.

**Comment by 0mp** [comment]
Kilka wskazówek jest już w masterze. Zamyka więc ten wątek. Dzięki!
